### ISSUE TITLE
Warning: non trusted contribution...

### ISSUE THREAD

**Issue by SalvorinFex** [femtoduino/ArduinoCore-atsamd21e18a#17]
Howdy, I keep getting this error message when installing the Boards Manager item for Femto:

Warning: non trusted contribution, skipping script execution (C:\Users\USER_NAME\AppData\Local\Arduino15\packages\femtoduino\hardware\samd\1.7.7\post_install.bat)

Is this standard or something that can be fixed?

**Comment by zrecore** [comment]
It's a file from upstream (ArduinoCore-samd)

You can safely ignore it, as you must install the Arduino SAMD (ARM Cortex
M0+) board package v1.6.11 to use this board package anyway.

**Comment by SalvorinFex** [comment]
OKay, thanks for the info
