### ISSUE TITLE
Fatal error: Arduino.h: No such file or directory

### ISSUE THREAD

**Issue by benlhy** [femtoduino/ArduinoCore-atsamd21e18a#18]
I was attempting to compile the following sketch in Arduino:

`void setup() {
  // put your setup code here, to run once:
  pinMode(1,OUTPUT);

}

void loop() {
  // put your main code here, to run repeatedly:

digitalWrite(1,HIGH);
}`

However, it yields the error Arduino.h: No such file or directory.

**Comment by zrecore** [comment]
Which board do you have selected?

**Comment by benlhy** [comment]
Seems like the Arduino Cortex library was messed up. I removed it and reinstalled it and I can compile the code successfully now!

**Comment by zrecore** [comment]
Excellent!
