### ISSUE TITLE
Missing ,

### ISSUE THREAD

**Issue by Spomky** [femtoduino/ArduinoCore-atsamd21e18a#19]
Hi,

I received the 5 pieces kit and started to setup my env (Ubuntu 18.04 desktop).
Thank you for the quick delivery by the way.
It looks like the file at https://downloads.femtoduino.com/ArduinoCore-atsamd21e18a/package_atsamd21e18a-release-build_index.json is not valid.
There is a missing `,` at line 367

```json
             "packager": "arduino",
              "name": "bossac",
              "version": "1.7.0"
            },
            {
              "packager": "arduino",
              "name": "openocd",
              "version": "0.9.0-arduino"
            },
            {
              "packager": "arduino",
              "name": "CMSIS",
              "version": "4.0.0-atmel"
            }
          ]
        } <===== HERE










        {
          "name": "Atmel SAM D21E/R21E core",
          "architecture": "samd",
          "version": "1.8.0",
```

No problem with the one at https://downloads.femtoduino.com/ArduinoCore-atsamd21e18a/package_atsamd21e18a-hourly-build_index.json

Regards

**Comment by zrecore** [comment]
Thank you for letting me know. I've remedied the issue.
