### ISSUE TITLE
FreeIMUUtils/CommunicationUtils.cpp should not use %s to buffer in non-ASCII output

### ISSUE THREAD

**Issue by drogge** [femtoduino/ArduinoCore-atsamd21e18a#21]
The toPrintableArr function used to buffer the IMU data in the 'b' command ends up using the %s printf format to try to add a byte to output buffer. This would cause the byte to be interpreted as a char * and  some random amount of garbage will be copied to the buffer. Probably overflowing into adjacent memory.

**Comment by zrecore** [comment]
Ah, that explains the occasional random garbage then. :-)

**Comment by drogge** [comment]
I'm not sure that the FemtoCore code is actually able to handle transmitting raw data. In the case of the 'b' command the buffer with the raw data is handed off to _reply which assumes the buffer contains ASCII chars. The calls to sprintf would probably yield unexpected results with raw data. 

If you're going to be sending raw data then lots of functions are going to have to not depend on dealing with NULL terminated strings. This include send, broadcast, _networkingSendMessage* and maybe more. 

You might want to think about not supporting raw data for now.

**Comment by zrecore** [comment]
Makes sense. The raw data function was originally a FreeIMU Serial command.
