### ISSUE TITLE
Card femtobeaconpro (plateform samd, package femtoduino) is unknown

### ISSUE THREAD

**Issue by Spomky** [femtoduino/ArduinoCore-atsamd21e18a#25]
Hi,

I followed the installation steps [on this page](https://femtoduino.com/examples/setup) and [here](https://github.com/femtoduino/ArduinoCore-atsamd21e18a#installation-on-arduino-ide) but I cannot compile my source code.

I’ve got the following error:

> Card femtobeaconpro (plateform samd, package femtoduino) is unknown
> Compilation error for the card FemtoBeacon PRO - SAM R21E (Native USB Port)

Arduino AVR Boards v1.6.23
Arduino SAMD boards (32-bits ARM Cortex-M0+) v1.6.19
Atmel SAM D21/R21E v1.8.2

Any idea?

**Comment by zrecore** [comment]
Please let me know if you would like to schedule a Google Hangout session (when and what time zone) via support@femtoduino.com

**Comment by Spomky** [comment]
Hi,

I removed all files in the folder `.arduino15` and re-installed everything and now the compilation is correctly done… but only with the hourly build.
With the last stable release (1.8.4) I have the same error as in #26.

Let’s continue the discussion in that new thread.
