### ISSUE TITLE
'PIN_SPI_IRQ' was not declared in this scope

### ISSUE THREAD

**Issue by kitylam9** [femtoduino/ArduinoCore-atsamd21e18a#32]
Hello developer,
I try the all the coin example with FemtoBeacon, while I compile the program, it return the error:

` 'PIN_SPI_IRQ' was not declared in this scope, `

===============================================================
The code that use this variable normally from this line of code:

  `SPI.usingInterrupt(digitalPinToInterrupt(PIN_SPI_IRQ));`
and also:
` attachInterrupt(digitalPinToInterrupt(PIN_SPI_IRQ), HAL_IrqHandlerSPI, RISING);`

May I ask how to solve this problem?

**Comment by kitylam9** [comment]
Another issue:
'MODULE_AT86RF233_CLOCK' was not declared in this scope

**Comment by zrecore** [comment]
Make sure the "FemtoBeacon Pro" board is selected
