### ISSUE TITLE
Error(s) Cloning Repository

### ISSUE THREAD

**Issue by jwestmoreland** [femtoduino/ArduinoCore-atsamd21e18a#34]
Hello,

I've tried to clone this repository - and am getting the following error(s):

git.exe clone --progress --recursive -v "https://github.com/femtoduino/ArduinoCore-atsamd21e18a.git" "F:\femto\ArduinoCore-atsamd21e18a"
Cloning into 'F:\femto\ArduinoCore-atsamd21e18a'...
POST git-upload-pack (375 bytes)
remote: Enumerating objects: 8411, done.
remote: Total 8411 (delta 0), reused 0 (delta 0), pack-reused 8411
Receiving objects: 100% (8411/8411), 23.38 MiB | 27.20 MiB/s, done.
Resolving deltas: 100% (4571/4571), done.
Checking out files: 100% (1748/1748), done.
Submodule 'libraries/RTCZero' (git@github.com:femtoduino/RTCZero.git) registered for path 'libraries/RTCZero'
Submodule 'libraries/atmel-lwm' (git@github.com:femtoduino/library-atmel-lwm.git) registered for path 'libraries/atmel-lwm'
Cloning into 'F:/femto/ArduinoCore-atsamd21e18a/libraries/RTCZero'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:femtoduino/RTCZero.git' into submodule path 'F:/femto/ArduinoCore-atsamd21e18a/libraries/RTCZero' failed
Failed to clone 'libraries/RTCZero'. Retry scheduled
Cloning into 'F:/femto/ArduinoCore-atsamd21e18a/libraries/atmel-lwm'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:femtoduino/library-atmel-lwm.git' into submodule path 'F:/femto/ArduinoCore-atsamd21e18a/libraries/atmel-lwm' failed
Failed to clone 'libraries/atmel-lwm'. Retry scheduled
Cloning into 'F:/femto/ArduinoCore-atsamd21e18a/libraries/RTCZero'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:femtoduino/RTCZero.git' into submodule path 'F:/femto/ArduinoCore-atsamd21e18a/libraries/RTCZero' failed
Failed to clone 'libraries/RTCZero' a second time, aborting

git did not exit cleanly (exit code 1) (51281 ms @ 6/11/2020 3:34:05 AM)

Thanks In Advance,
John W.

**Comment by zrecore** [comment]
Hi John! Thank you for filing an issue! Ok, I'm trying to reproduce the issue by doing a clean checkout using the same flags and values shown:
(I've made a folder in my Downloads directory named 'arduino-core-test', and from there I run..)
```
git clone --progress --recursive -v "https://github.com/femtoduino/ArduinoCore-atsamd21e18a.git" "./ArduinoCore-atsamd21e18a"
```
It seems to have succeeded. Here's the output:

```
Cloning into './ArduinoCore-atsamd21e18a'...
POST git-upload-pack (365 bytes)
remote: Enumerating objects: 8411, done.
remote: Total 8411 (delta 0), reused 0 (delta 0), pack-reused 8411
Receiving objects: 100% (8411/8411), 23.38 MiB | 6.19 MiB/s, done.
Resolving deltas: 100% (4571/4571), done.
Submodule 'libraries/RTCZero' (git@github.com:femtoduino/RTCZero.git) registered for path 'libraries/RTCZero'
Submodule 'libraries/atmel-lwm' (git@github.com:femtoduino/library-atmel-lwm.git) registered for path 'libraries/atmel-lwm'
Cloning into '/Users/aalbino/Downloads/arduino-core-test/ArduinoCore-atsamd21e18a/libraries/RTCZero'...
remote: Enumerating objects: 311, done.        
remote: Total 311 (delta 0), reused 0 (delta 0), pack-reused 311        
Receiving objects: 100% (311/311), 52.11 KiB | 860.00 KiB/s, done.
Resolving deltas: 100% (151/151), done.
Cloning into '/Users/aalbino/Downloads/arduino-core-test/ArduinoCore-atsamd21e18a/libraries/atmel-lwm'...
remote: Enumerating objects: 7, done.        
remote: Counting objects: 100% (7/7), done.        
remote: Compressing objects: 100% (7/7), done.        
remote: Total 324 (delta 1), reused 3 (delta 0), pack-reused 317        
Receiving objects: 100% (324/324), 121.36 KiB | 682.00 KiB/s, done.
Resolving deltas: 100% (188/188), done.
Submodule path 'libraries/RTCZero': checked out '83bac92a3e01bc077a0d88a7271df32c1cca3f21'
Submodule path 'libraries/atmel-lwm': checked out '8f425671132aab051d46af387ad137b3f651b838'
aalbino@Alejandros-MacBook-Pro arduino-core-test % git clone --progress --recursive -v "https://github.com/femtoduino/ArduinoCore-atsamd21e18a.git" "./ArduinoCore-atsamd21e18a"
```

Possible things to check: There may be a problem with your machine's network setup?

**Comment by jwestmoreland** [comment]
Hello @zrecore (Alex),

I tried again - moved to another drive JIC - but am still seeing issues.

The two directories that I'm having issues with both seem to have the commit tag embedded in their names under ./libraries - not sure if that's the/an issue or not.

I just did a commit to Amazon code commit for a repository I'm working on - if I was having network/machine issues; that would have failed.

The clone is looking for credentials - you will see that in the attached - so, not sure what's going on there as I haven't set up security credentials for github for repos I'm not responsible for per se.

I see the last line of your check-out/clone appears to have your user name in it - implying a log in with credentials maybe?
[
I assume this core port to the d21e18a is working well - correct?  If I can slip in another question here as I'm working on a new design where this part is a good fit and I'd like to make it Arduino compatible.  (thanks...)
]
Thanks,
John W.
![screenshot](https://user-images.githubusercontent.com/2308903/84448826-951e7480-ac00-11ea-91bd-11a599d3bde9.jpg)

**Comment by zrecore** [comment]
Ah! Ok...I think i'll need to update the git remote url value of those submodules. They should be https urls instead.

**Comment by zrecore** [comment]
You will need to remove the checkout from your machine, and attempt to clone the repository again. I've pushed a .gitmodule change in bc1e5b5d6698b8ff4e1d5b8bfa879d057366bf8b to the master branch

**Comment by jwestmoreland** [comment]
Hello Alex,

Working now:
git.exe clone --progress --recursive -v "https://github.com/femtoduino/ArduinoCore-atsamd21e18a.git" "C:\femto\ArduinoCore-atsamd21e18a"
Cloning into 'C:\femto\ArduinoCore-atsamd21e18a'...
POST git-upload-pack (375 bytes)
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 8414 (delta 0), reused 1 (delta 0), pack-reused 8411
Receiving objects: 100% (8414/8414), 23.38 MiB | 18.89 MiB/s, done.
Resolving deltas: 100% (4571/4571), done.
Checking out files: 100% (1748/1748), done.
Submodule 'libraries/RTCZero' (https://github.com/femtoduino/RTCZero.git) registered for path 'libraries/RTCZero'
Submodule 'libraries/atmel-lwm' (https://github.com/femtoduino/library-atmel-lwm.git) registered for path 'libraries/atmel-lwm'
Cloning into 'C:/femto/ArduinoCore-atsamd21e18a/libraries/RTCZero'...
remote: Enumerating objects: 311, done.
remote: Total 311 (delta 0), reused 0 (delta 0), pack-reused 311
Receiving objects: 100% (311/311), 52.11 KiB | 1.74 MiB/s, done.
Resolving deltas: 100% (151/151), done.
Cloning into 'C:/femto/ArduinoCore-atsamd21e18a/libraries/atmel-lwm'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 324 (delta 1), reused 3 (delta 0), pack-reused 317
Receiving objects: 100% (324/324), 121.36 KiB | 3.91 MiB/s, done.
Resolving deltas: 100% (188/188), done.
Submodule path 'libraries/RTCZero': checked out '83bac92a3e01bc077a0d88a7271df32c1cca3f21'
Submodule path 'libraries/atmel-lwm': checked out '8f425671132aab051d46af387ad137b3f651b838'

Success (9046 ms @ 6/11/2020 4:52:29 PM)

Thanks,
John W.
