### ISSUE TITLE
Program SAM R21 Xplained Pro

### ISSUE THREAD

**Issue by beriberikix** [femtoduino/ArduinoCore-atsamd21e18a#5]
I have a few of the Xplained Pro devkits and was wondering how to program them with this core. Do I need to first program it with a different bootloader?

**Comment by zrecore** [comment]
The Xplained PRO (SAM D21, G variant) can use the same bootloader as the
Arduino Zero.


My fork is meant for the smaller SAM D21 and R21 "E" Variants.
